@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Tambah Transaksi</h1>
    @if(session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif

    @if(session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <form id="transaction-form" action="{{ route('sales.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="kode">No Transaksi</label>
                    <input type="text" name="kode" id="kode" class="form-control" value="{{ $autoGeneratedKode }}" readonly>
                </div>

                <div class="form-group">
                    <label for="tgl">Tanggal</label>
                    <input type="date" name="tgl" id="tgl" class="form-control" value="{{ now()->format('Y-m-d') }}" required>
                </div>

                <div class="form-group">
                    <label for="customer_id">Customer</label>
                    <input type="hidden" name="cust_id" id="cust_id">
                    <input type="text" name="customer_kode" id="customer_kode" class="form-control" readonly>
                    <input type="text" name="customer_name" id="customer_name" class="form-control mt-2" readonly>
                    <input type="text" name="customer_telp" id="customer_telp" class="form-control mt-2" readonly>
                    <button type="button" class="btn btn-primary mt-2" id="select-customer">Pilih Customer</button>
                </div>
            </div>
        </div>

        <h2 class="mt-4">Detail Transaksi</h2>
        <div class="table-responsive">
            <table class="table table-bordered" id="details-table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Kode Barang</th>
                        <th>Nama Barang</th>
                        <th>QTY</th>
                        <th>Harga Bandrol</th>
                        <th>Diskon (%)</th>
                        <th>Diskon (RP)</th>
                        <th>Harga Diskon</th>
                        <th>Total</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody id="details-table-body">
                    <!-- Rows will be added here -->
                </tbody>
            </table>
        </div>

        <button type="button" id="add-item-button" class="btn btn-primary mt-2">Tambah Barang</button>

        <div class="form-group mt-4">
            <label for="subtotal">Subtotal</label>
            <input type="number" name="subtotal" id="subtotal" class="form-control" value="0" readonly>
        </div>

        <div class="form-group">
            <label for="diskon">Diskon</label>
            <input type="number" name="diskon" id="diskon" class="form-control" value="0">
        </div>

        <div class="form-group">
            <label for="ongkir">Ongkir</label>
            <input type="number" name="ongkir" id="ongkir" class="form-control" value="0">
        </div>

        <div class="form-group">
            <label for="total_bayar">Total Bayar</label>
            <input type="number" name="total_bayar" id="total_bayar" class="form-control" value="0" readonly>
        </div>

        <button type="submit" class="btn btn-success mt-2">Simpan</button>
        <a href="{{ route('sales.index') }}" class="btn btn-secondary mt-2">Batal</a>
    </form>
</div>

<!-- Modal for selecting customer -->
<div class="modal fade" id="customerModal" tabindex="-1" aria-labelledby="customerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="customerModalLabel">Pilih Customer</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Kode</th>
                            <th>Nama</th>
                            <th>Telp</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($customers as $customer)
                        <tr data-kode="{{ $customer->kode }}" data-name="{{ $customer->name }}" data-telp="{{ $customer->telp }}">
                            <td>{{ $customer->kode }}</td>
                            <td>{{ $customer->name }}</td>
                            <td>{{ $customer->telp }}</td>
                            <td><button type="button" class="btn btn-primary select-customer">Pilih</button></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal for selecting item -->
<div class="modal fade" id="itemModal" tabindex="-1" aria-labelledby="itemModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="itemModalLabel">Pilih Barang</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Kode Barang</th>
                            <th>Nama Barang</th>
                            <th>Harga Bandrol</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($barangs as $barang)
                        <tr data-kode="{{ $barang->kode }}" data-name="{{ $barang->nama }}" data-harga="{{ $barang->harga }}">
                            <td>{{ $barang->kode }}</td>
                            <td>{{ $barang->nama }}</td>
                            <td>{{ number_format($barang->harga, 2) }}</td>
                            <td><button type="button" class="btn btn-primary select-item">Pilih</button></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Handle customer selection
        document.getElementById('select-customer').addEventListener('click', function() {
            $('#customerModal').modal('show');
        });

        document.querySelector('#customerModal').addEventListener('click', function(e) {
            if (e.target.classList.contains('select-customer')) {
                const customerRow = e.target.closest('tr');
                document.getElementById('customer_kode').value = customerRow.dataset.kode;
                document.getElementById('customer_name').value = customerRow.dataset.name;
                document.getElementById('customer_telp').value = customerRow.dataset.telp;
                document.getElementById('cust_id').value = customerRow.dataset.id;
                $('#customerModal').modal('hide');
            }
        });

        // Handle item selection
        document.getElementById('add-item-button').addEventListener('click', function() {
            $('#itemModal').modal('show');
        });

        document.querySelector('#itemModal').addEventListener('click', function(e) {
            if (e.target.classList.contains('select-item')) {
                const itemRow = e.target.closest('tr');
                const rowCount = document.getElementById('details-table-body').rows.length;
                let row = document.getElementById('details-table-body').insertRow();
                row.innerHTML = `
                    <td>${rowCount + 1}</td>
                    <td><input type="text" name="details[${rowCount}][barang_id]" value="${itemRow.dataset.kode}" readonly /></td>
                    <td><input type="text" name="details[${rowCount}][nama_barang]" value="${itemRow.dataset.name}" readonly /></td>
                    <td><input type="number" name="details[${rowCount}][qty]" value="1" class="qty" /></td>
                    <td><input type="number" name="details[${rowCount}][harga_bandrol]" value="${itemRow.dataset.harga}" class="harga_bandrol" readonly /></td>
                    <td><input type="number" name="details[${rowCount}][diskon_pct]" value="0" class="diskon_pct" /></td>
                    <td><input type="number" name="details[${rowCount}][diskon_nilai]" value="0" class="diskon_nilai" readonly /></td>
                    <td><input type="number" name="details[${rowCount}][harga_diskon]" value="${itemRow.dataset.harga}" class="harga_diskon" readonly /></td>
                    <td><input type="number" name="details[${rowCount}][total]" value="${itemRow.dataset.harga}" class="total" readonly /></td>
                    <td><button type="button" class="btn btn-danger remove-item">Hapus</button></td>
                `;
                $('#itemModal').modal('hide');
                updateTotals();
            }
        });

        // Handle removing items
        document.getElementById('details-table-body').addEventListener('click', function(e) {
            if (e.target.classList.contains('remove-item')) {
                e.target.closest('tr').remove();
                updateTotals();
            }
        });

        // Function to update subtotal, discount, and total
        function updateTotals() {
            let subtotal = 0;
            document.querySelectorAll('#details-table-body tr').forEach(function(row) {
                const qty = parseFloat(row.querySelector('.qty').value) || 0;
                const hargaBandrol = parseFloat(row.querySelector('.harga_bandrol').value) || 0;
                const diskonPct = parseFloat(row.querySelector('.diskon_pct').value) || 0;
                
                const diskonNilai = (qty * hargaBandrol) * (diskonPct / 100);
                const hargaDiskon = hargaBandrol - (diskonNilai / qty);
                const total = hargaDiskon * qty;

                row.querySelector('.diskon_nilai').value = diskonNilai.toFixed(2);
                row.querySelector('.harga_diskon').value = hargaDiskon.toFixed(2);
                row.querySelector('.total').value = total.toFixed(2);

                subtotal += total;
            });
            
            document.getElementById('subtotal').value = subtotal.toFixed(2);
            
            const diskonSummary = parseFloat(document.getElementById('diskon').value) || 0;
            const ongkir = parseFloat(document.getElementById('ongkir').value) || 0;

            const totalBayar = subtotal - diskonSummary + ongkir;
            document.getElementById('total_bayar').value = totalBayar.toFixed(2);
        }

        // Update totals on changes
        document.getElementById('details-table-body').addEventListener('input', updateTotals);
        document.getElementById('diskon').addEventListener('input', updateTotals);
        document.getElementById('ongkir').addEventListener('input', updateTotals);
    });
</script>

@endsection
